AllCops:
  TargetRubyVersion: 2.4.1
  DisplayCopNames: true
  Exclude:
    - config/**/*
    - db/**/*
    - vendor/**/*
    - lib/**/*
    - spec/**/*
    - app/views/**/*

Metrics/LineLength:
  Max: 111

Style/Documentation:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false  

Lint/EndAlignment:
  EnforcedStyleAlignWith: variable

Lint/RescueException:
  Enabled: false

Style/SymbolProc:
  Enabled: false

Lint/ParenthesesAsGroupedExpression:
  Enabled: false

Layout/TrailingWhitespace:
  Enabled: false

Style/Alias:
  Enabled: false

Rails/FilePath:
  Enabled: false
